with source_data as (
    select * from {{ source('fantasyfootball', 'nflfastr_pbp')}}
),

pbp as (
    select
        play_id,
        game_id,
        home_team,
        away_team, 
        season_type,
        season, 
        week,
        posteam,
        posteam_type,
        defteam,
        side_of_field, 
        yardline_100, 
        game_date,
        game_half,
        qtr,
        down,
        goal_to_go,
        ydstogo,
        play_type,
        yards_gained,
        shotgun,
        no_huddle,
        qb_kneel,
        qb_spike,
        qb_scramble, 
        pass_location,
        air_yards,
        yards_after_catch,
        run_location,
        two_point_conv_result,
        td_player_name, -- remove once we have rosters
        td_player_id,
        interception,
        safety,
        tackled_for_loss,
        fumble, 
        fumble_lost, 
        sack,
        touchdown,
        pass_touchdown,
        rush_touchdown,
        two_point_attempt,
        complete_pass,
        passer_player_id,
        passer_player_name, 
        passer, 
        passer_id, 
        passing_yards,
        receiver_player_id,
        receiver_player_name,
        receiver, 
        receiver_id, 
        receiving_yards, 
        rusher_player_id,
        rusher_player_name,
        rusher, 
        rusher_id, 
        rushing_yards,
        cp,
        cpoe

    from source_data
)

select * from pbp